services:
  localstack:
    image: gresau/localstack-persist:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - "./my-localstack-data:/persisted-data"
  chromadb:                                                                                                                                                                                                                                                                                                                      
    volumes:                                                                                                                                                                      
      - ./data/chroma_db:/data
  streamlit:                                                                                                                                                                         
    volumes:                                                                                                                                                                         
      - ./src:/app/src                                                                                                                                         
  inference_service:
    env_file:                                                                                                                                                                          
      - .env                                                                                                                                                                           
      - config/params.env
    volumes:                                                                                                                                                                        
      - ./data:/app/data
      - ./src:/app/src
    environment:
      - DMS_URL=http://document_management_service:8000
  ingestion_service:
    volumes:                                                                                                                                                                        
      - ./data:/app/data
      - ./src:/app/src
    env_file:                                                                                                                                                                          
      - .env                                                                                                                                                                           
      - config/params.env
    environment:
      - DMS_URL=http://document_management_service:8000
  document_management_service:                                                                                                                                                         
    volumes:                                                                                                                                                                           
      - ./src:/app/src     
  pact-broker:
    image: pactfoundation/pact-broker:latest
    ports:
      - "9292:9292"
    environment:
      PACT_BROKER_DATABASE_ADAPTER: sqlite
      PACT_BROKER_DATABASE_URL: "sqlite:////tmp/pact_broker.sqlite3"
    volumes:
      - pact-broker-data:/tmp
  dms-db:
    environment:
      POSTGRES_DB: dms
      POSTGRES_USER: dms
      POSTGRES_PASSWORD: dms
    volumes:                                                                                                                                                                           
      - ./data/dms-db:/var/lib/postgresql/data
volumes:
  pact-broker-data: