FROM python:3.11-slim

WORKDIR /app

COPY src/ui_service/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src/ui_service/streamlit_app.py src/ui_service/streamlit_app.py

CMD ["streamlit", "run", "src/ui_service/streamlit_app.py"]