FROM python:3.11-slim

WORKDIR /app

COPY src/ui_service/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src/__init__.py src/__init__.py
COPY src/ui_service src/ui_service
COPY .streamlit .streamlit

CMD ["streamlit", "run", "src/ui_service/streamlit_app.py"]